name: Update README local time (SGT)

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:         # allow manual run

jobs:
  update-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Update time between markers
        run: |
          export TZ=Asia/Singapore
          NOW="$(date '+%Y-%m-%d %H:%M:%S %z')"
          FILE="README.md"
          START="<!--TIME-->"
          END="<!--ENDTIME-->"
          # Replace everything between START and END (keeping the markers)
          perl -0777 -pe "s/${START}.*?${END}/${START} ${NOW} ${END}/s" -i "$FILE"

      - name: Commit changes if any
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update local time (SGT)"
            git push
          else
            echo "No changes to commit."
          fi
