name: Update README with Time

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # 👈 gives permission to push changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README
        run: |
          TIME=$(TZ=Asia/Singapore date +"%Y-%m-%d %H:%M:%S %Z")
          sed -i "s|<!--TIME-->.*<!--ENDTIME-->|<!--TIME--> $TIME <!--ENDTIME-->|" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update time" || echo "No changes to commit"
          git push
